### ISSUE TITLE
Text looks Blurred on Android device

### ISSUE THREAD

**Issue by cyclops24** [JoeyAndres/meteor-ionic#9] opened 2016-02-06 05:16 UTC
Hi @JoeyAndres ,
I have same issue with [this stackoverflow question](http://stackoverflow.com/questions/24492490/text-looks-blurred-and-cheap-in-android-hybrid-app-using-ionic-framework) when use ionic in meteor.
In the past when I used ionic alone I didn't have this issue.

When app runs on the real device some text blurred and unclear line above stackoverflow question image.
Can you any idea about this?

**Comment by JoeyAndres** [comment] 2016-02-08 08:20
I'll look into http://stackoverflow.com/a/30162817 answer tomorrow. This is indeed interesting. This is because all ion-content have 'scroll-content ionic-scroll' classes, which perfectly matches his description. I'll let you know when I get to this.

**Comment by cyclops24** [comment] 2016-02-08 16:31
@JoeyAndres I test that answer and it not working for me. Please give me the news.

**Comment by JoeyAndres** [comment] 2016-05-09 00:31
@cyclops24 I don't know how to solve this. I simply can't reproduce this. I'll close this for now.

**Closed as completed** 2016-05-09 00:32 UTC
Labels: native
